### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by JakobMiksch** [meggsimum/qgis2wegue#10]

**Comment by chrismayer** [comment]
Could be somehow related to https://github.com/meggsimum/wegue/issues/116

**Comment by JakobMiksch** [comment]
added temporary logo with 5132e8c29e895230707d5f0f7788f89d7fac5be0

![logo](https://user-images.githubusercontent.com/15704517/77761016-9eebff00-7037-11ea-9950-7629ee846add.png)
