### ISSUE TITLE
ModuleNotFoundError: No module named 'unidecode'

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/qgis2wegue#16]
Based on current master (4c7fa30431109d8bb65166416195ec19476f3b20) the following error is shown on QGIS startup: `ModuleNotFoundError: No module named 'unidecode'`

**Comment by JakobMiksch** [comment]
maybe replace with ~~`chardet`~~, `pyparsing` or `idna` which is built-in to QGIS

**Comment by JakobMiksch** [comment]
fixed with d03e203cb184973870b6e704eec6526b31e7184a
@chrismayer now it should work on your machine ;-)

**Comment by chrismayer** [comment]
@JakobMiksch No luck, an other error occurred, see #20
