### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by JakobMiksch** [meggsimum/qgis2wegue#2]
## General

- [x] Window size should be constant

## Filepath hints
- [x] handle empty filepath
- [x] filepath should end with `.json`
- [x] tell user that Wegue configs are typically named like: `app-conf-nationalpark.json`
- [x] show user which fields are optional

## Internet
- [x] check if internet is availabe, since it might be needed for `OWSlib` and maybe other functions
       --> I think not necessary, because I cannot image a scenario where the user has not access to his/her remote WMS/WFS layers

**Comment by JakobMiksch** [comment]
pretty much fixed with dd49af7d53b75e3cfef01fd0e0d38e37db82cefa
@chrismayer what do you think?

**Comment by chrismayer** [comment]
Yeah, I just tested. It looks good to me. Thanks @JakobMiksch !

**Comment by JakobMiksch** [comment]
I additionally made the windows size constant 792340b12cd65a340462560954f36ac798d559c2
because IMHO changing the window size is not necessary
