### ISSUE TITLE
WMS: retrieve "GetMap"-URL

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/qgis2wegue#20]
When using the current master (c7bbb02bdfafac39d97461754e2a450b6de3c6ed) with QGIS 3.12 I get the follwoing error stack when opening the plugin:

```
AttributeError: 'NoneType' object has no attribute 'groups' 
Traceback (most recent call last):
  File "/home/meggs/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2wegue/qgis2wegue.py", line 198, in run
    wc = create_wegue_conf_from_qgis(canvas)
  File "/home/meggs/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2wegue/wegue_util.py", line 49, in create_wegue_conf_from_qgis
    url = get_wms_getmap_url(layer)
  File "/home/meggs/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2wegue/wegue_util.py", line 202, in get_wms_getmap_url
    layersGroup = match.groups(0)
AttributeError: 'NoneType' object has no attribute 'groups'
``` 

![grafik](https://user-images.githubusercontent.com/1185547/77508805-dc039600-6e6b-11ea-8662-65d7aa3c88bd.png)

**Comment by JakobMiksch** [comment]
@chrismayer  Could you tell me which layers you used?
Because I tried it on both Windows and Linux and it worked. But I guess I will create a sample project with all kind of layers, including layers with uncommon properties. This should make sure that the plugin also works for edge cases ...

**Comment by chrismayer** [comment]
- https://www.geoportal.rlp.de/mapbender/php/wms.php?inspire=1&layer_id=69694&withChilds=1&INSPIRE=1&
- https://sgx.geodatenzentrum.de/wms_topplus_open?
- https://opendata.geoportal.rlp.de/mapbender/php/wms.php?layer_id=61675& (NOT VISIBLE)
- http://ows.terrestris.de/osm/service?

**Comment by JakobMiksch** [comment]
This commit should fix it dee7faa435479cc212de3eca4fb64fe9d41d6164
However, it is a bit strange. I could reproduce it on Windows but not on my Ubuntu machine.
@chrismayer could you check again if it works?

**Comment by chrismayer** [comment]
I runs now without error because of your check, but the problem is just moved. The responsible layer "Nord" is exported with the wrong GetMap URL (the WMS base URL, what is not correct here). 

The root cause is IMHO this commit: e8817bd1c2d11c2eadbc0f1 It screws up the detection of the GetMap URL and uses the WMS base URL as fallback. This works for all WMS, which use the base URL for all request types. If this is not the case it breaks, like in layer "Nord" (https://www.geoportal.rlp.de/mapbender/php/wms.php?inspire=1&layer_id=69694&withChilds=1&INSPIRE=1&)

When I revert  e8817bd1c2 everything works as expected.

**Comment by chrismayer** [comment]
OK, did some investigations: The tag used in the HTML metadata, which is used to derive the GetMap URL is translated. So for my German setup it is `GetMap-URL` and in English it is `GetMapURL`. So it seems we have to derive the term for our regex from the i18n-engine / -config.

That's why e8817bd works for you @JakobMiksch and does not for me.

**Comment by JakobMiksch** [comment]
@chrismayer I tried it with OWSlib(which is preinstalled in QGIS) and it should work. See here: https://github.com/JakobMiksch/qgis2wegue/commit/74bde4386f68cf62053d6f73b1ba294c7044ec29  You can try it on this branch [wms-getmap-fix](https://github.com/JakobMiksch/qgis2wegue/tree/wms-getmap-fix). The code is much shorter and cleaner.

However, the downside is that OWSlib queries the WMS again and creates a short but noticable processing time of the plugin.  Moreover the user needs to be online, what should be fine IMHO.

**Comment by chrismayer** [comment]
The GetMap URL detection works now on my setup. But the layer order is messed up again. Not sure if this is related to the changes in `wms-getmap-fix`.

The following layer stack is defined in QGIS:
![grafik](https://user-images.githubusercontent.com/1185547/78107629-264dbf80-73f6-11ea-96ab-0b9bcb0a3a8b.png)

This is what I get in Wegue:
![grafik](https://user-images.githubusercontent.com/1185547/78107693-3fef0700-73f6-11ea-9fdb-0bb601e9e188.png)

**Comment by JakobMiksch** [comment]
I added the commit to the master: 17a1a6ad9ad6273c77659e353acdb6217a513c9d
Layer order seems to be fine for me.
@chrismayer let me know if you still have troubles
