### ISSUE TITLE
WMS TopPlusOpen cannot be exported

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/qgis2wegue#22]
The WMS TopPlusOpen (https://sgx.geodatenzentrum.de/wms_topplus_open?) cannot be exported:

![grafik](https://user-images.githubusercontent.com/1185547/80342734-f5ca3b80-8864-11ea-864a-4c608da287f2.png)

Not sure if this is a problem of qgis2wegue (due to OWSLib) or of the service itself since it already worked in a prev. stage.

**Comment by JakobMiksch** [comment]
I tried it on both Windows and Debian and it work for me.
@chrismayer could you try  again?

**Comment by chrismayer** [comment]
Yes, I tried it again and it works now. Maybe a temp. issue with the service itself.
