### ISSUE TITLE
New logo draft

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/qgis2wegue#25]
I created a new draft for a logo. Intention was to have a visual mention of QGIS in the logo:

![image](https://user-images.githubusercontent.com/1185547/81376951-c806b180-9104-11ea-9005-0ec960376e86.png)

In case you like it I can provide a PR with a larger image and a SVG version.

What do you think @JakobMiksch

**Comment by chrismayer** [comment]
Or the other way round

![image](https://user-images.githubusercontent.com/1185547/81383105-c098d580-910f-11ea-8b5e-6ee76ede2b68.png)

![image](https://user-images.githubusercontent.com/1185547/81383173-e1f9c180-910f-11ea-91ea-cf71d749ba0c.png)

**Comment by JakobMiksch** [comment]
good idea - we have to take in mind that the logo is mostly seen as super small icon in the toolbar. Hence, details cannot really be seen by the user. I will try it

**Comment by chrismayer** [comment]
Right, we should test it in the icon view in the toolbar. Do you have a preference for a version?

**Comment by JakobMiksch** [comment]
Here how it looks in the toolbar:
![image](https://user-images.githubusercontent.com/15704517/81493526-3c765780-92a1-11ea-82c2-55f236e7f91e.png)
![image](https://user-images.githubusercontent.com/15704517/81493488-fc16d980-92a0-11ea-9555-fd308248daac.png)
![image](https://user-images.githubusercontent.com/15704517/81493509-1fda1f80-92a1-11ea-8471-087240669942.png)

the second version looks best to me

**Comment by chrismayer** [comment]
In general it looks better than I expected as small icon in the toolbar. Agree that the 2nd one looks best.

**Comment by JakobMiksch** [comment]
closed with 1eb90684052a1ff28f97e82e9f303bfa340336eb
