### ISSUE TITLE
Install instructions needed

### ISSUE THREAD

**Issue by tsmcgrath** [meggsimum/qgis2wegue#31]
Hi, I've found Wegue just this weekend. Looks great. I'm trying to customize it so I can evaluate using it. I'm a Vue newbie and relative JS/TS newbie. I installed the QGIS2Wegue plug-in and output a config file to test. Now I just need to know where to put it. I replaced the app-conf.json in wegue/app/static but that didn't work. I just added it as an additional config but that didn't seem to work either. I am more than happy to submit a pull request to the docs with an update on where to install - if you let me know where that is.

This is the config file the plug-in generated.
``
{
  "title": "US-WFS-Aquifers",
  "baseColor": "rgb(204, 0, 0)",
  "logo": "https://dummyimage.com/100x100/aaa/fff&text=Wegue",
  "logoSize": 100,
  "footerTextLeft": "",
  "footerTextRight": "",
  "showCopyrightYear": true,
  "mapZoom": 3,
  "mapCenter": [
    -12512434.051500008,
    4170027.4796292493
  ],
  "mapLayers": [
    {
      "type": "WFS",
      "name": "Aquifers",
      "url": "http://gstore.unm.edu/apps/rgisarchive/datasets/3205beb6-3406-4293-adef-a59ff0575965/services/ogc/wfs?VERSION",
      "lid": "aquifers",
      "style": {
        "strokeColor": "gray",
        "strokeWidth": 1,
        "fillColor": "rgba(20,20,20,0.1)"
      },
      "typeName": "aquifrp025",
      "extent": [
        -160.236053,
        17.674693,
        -64.566162,
        49.38562
      ]
    },
    {
      "type": "XYZ",
      "name": "OSM Standard",
      "url": "http://tile.openstreetmap.org/{z}/{x}/{y}.png",
      "lid": "osm_standard",
      "attributions": ""
    }
  ],
  "modules": {
    "wgu-layerlist": {
      "target": "menu",
      "win": true,
      "draggable": false
    },
    "wgu-infoclick": {
      "target": "menu",
      "win": true,
      "draggable": false,
      "initPos": {
        "left": 8,
        "top": 74
      }
    },
    "wgu-helpwin": {
      "target": "toolbar",
      "darkLayout": true
    },
    "wgu-measuretool": {
      "target": "menu",
      "win": true,
      "draggable": false,
      "strokeColor": "#c62828",
      "fillColor": "rgba(198,40,40,0.2)",
      "sketchStrokeColor": "rgba(198,40,40,0.8)",
      "sketchFillColor": "rgba(198,40,40,0.1)",
      "sketchVertexStrokeColor": "#c62828",
      "sketchVertexFillColor": "rgba(198,40,40,0.2)"
    },
    "wgu-zoomtomaxextent": {
      "target": "toolbar",
      "darkLayout": true
    },
    "wgu-geocoder": {
      "target": "toolbar",
      "darkLayout": true,
      "minChars": 2,
      "queryDelay": 200,
      "selectZoom": 16,
      "debug": false,
      "placeHolder": "Search address",
      "provider": "osm",
      "providerOptions": {
        "lang": "en-US",
        "countrycodes": "",
        "limit": 6
      }
    },
    "wgu-geolocator": {
      "target": "toolbar",
      "darkLayout": true
    }
  },
  "mapGeodataDragDop": {
    "formats": [
      "GeoJSON",
      "KML"
    ],
    "zoomToData": true,
    "replaceData": true,
    "displayInLayerList": true,
    "layerName": "Uploaded Data"
  },
  "permalink": {
    "location": "hash",
    "layers": true,
    "extent": false,
    "projection": "EPSG:4326",
    "paramPrefix": "",
    "history": true
  }
}
``

**Comment by JakobMiksch** [comment]
Hi @tsmcgrath great that you are trying Wegue. 
The config file that the QGIS plugin is creating is a bit outdated, because there has been some change with the config file of Wegue recently. 
My suggestion would be to start with the "minimal" config file (https://github.com/meggsimum/wegue/blob/master/app-starter/static/app-conf-minimal.json) and then step by step replace the settings with the configurations you created.

**Comment by tsmcgrath** [comment]
Also there are config files in wegue/app-starter/static. Not sure whether to add in that directory as well. Do I need to rebuild to apply it? I guess that would make sense.

**Comment by tsmcgrath** [comment]
Wow, thanks for the quick reply Jakob! Great suggestion. But then I guess I need to re-build, right?

**Comment by JakobMiksch** [comment]
Once your Wegue app is running, you can replace/change your config file and the refresh your browser where the Wegue app is running. Then the changes should apply

**Comment by tsmcgrath** [comment]
So, do I just have one config file in that app/static directory? How does it know which config to use?

**Comment by JakobMiksch** [comment]
You can have multiple config files in your directory. You can specify which one to open by adjusting your URL.
- The `app-conf.json` opens in `localhost:8081`
- others like `app-conf-minimal.json` open in `localhost:8081?appCtx=minimal`

This feature might be a bit hidden :-)

Recently we published a workshop about Weuge: https://meggsimum.github.io/wegue/#/workshop
There many concepts of Wegue are practically explained

**Comment by tsmcgrath** [comment]
Awesome. Thank you.
