### ISSUE TITLE
 classFactory() Methode error....

### ISSUE THREAD

**Issue by InspireGeo** [meggsimum/qgis2wegue#35]
I tried to install it but unfortunately I got the following error message.....

Konnte Erweiterung 'qgis2wegue' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode

**Comment by InspireGeo** [comment]
solved

**Comment by JakobMiksch** [comment]
@InspireGeo alright. Thanks for letting us know.

**Comment by JakobMiksch** [comment]
@InspireGeo Was the error related to the plugin?
Because, then we could fix it for future usage
