### ISSUE TITLE
Add WFS layer type

### ISSUE THREAD

**Issue by JakobMiksch** [meggsimum/qgis2wegue#6]
basic version already in 4806353ab9c330eb9366fbfc8fe0a98d86a2d6b7

- [x] create working prototype
- [x] add extent and maybe CRS

```python
extent = layer.extent()
crs = layer.crs()
```

- [x] check  if default values are properly set
- [x] check if there is a best-practice solution for retrieving WFS properties. Current solution works but is quite "pragmatic"  --> works and should be fine
- [x] Update README

**Comment by JakobMiksch** [comment]
the WFS creation seems to work
@chrismayer Shall we extract the CRS and the extent from QGIS as well?

**Comment by chrismayer** [comment]
> @chrismayer Shall we extract the CRS and the extent from QGIS as well?

Yes, seems like a good idea.

**Comment by JakobMiksch** [comment]
finally done in 4806353ab9c330eb9366fbfc8fe0a98d86a2d6b7 and 121695a30523f6aa2e1c259cfbb97e25800569e7
