### ISSUE TITLE
Only add layers that are visible in layer tree 

### ISSUE THREAD

**Issue by JakobMiksch** [meggsimum/qgis2wegue#7]
currently all layers if the QGIS project are chosen, independently if they are visible or not

related https://github.com/meggsimum/qgis2wegue/commit/fd677b7a1b12173e5acbf7078cbb65f69f87bc46

**Comment by chrismayer** [comment]
I think a better approach would be to transfer the visibility to the corresponding Wegue layer config property `"visible"`.

**Comment by JakobMiksch** [comment]
related https://github.com/meggsimum/qgis2wegue/commit/fd677b7a1b12173e5acbf7078cbb65f69f87bc46

**Comment by JakobMiksch** [comment]
https://github.com/meggsimum/qgis2wegue/commit/fd677b7a1b12173e5acbf7078cbb65f69f87bc46 this commit causes that only checked layers are included into the Wegue config. But we can still change this.

**Comment by chrismayer** [comment]
Maybe we wait for user feedback on this. Pretty unsure :wink:  I'd still pledge to transfer the visibility in QGIS to the corresponding Wegue layer config property "visible". But I am fine with your solution that only checked layers are included into the Wegue config for the moment. Let's see what the users say.

**Comment by JakobMiksch** [comment]
alright, then I close the issue. But we can re-open it anytime again ...
